import type { SkillsAssessmentSchema } from '@/server/endpoints/skills-assessment';

export const getDefaultSkillsAssessment = (): SkillsAssessmentSchema => {
    return {
        programmingLanguages: [
            {
                name: 'JavaScript',
                level: 0,
                subSkills: [
                    { name: 'TypeScript', level: 0 },
                    { name: 'Node.js', level: 0 },
                    { name: 'Express.js', level: 0 },
                    { name: 'React', level: 0 },
                    { name: 'Vue.js', level: 0 },
                    { name: 'Angular', level: 0 },
                    { name: 'Next.js', level: 0 },
                    { name: 'Playwright', level: 0 },
                    { name: 'Jest', level: 0 },
                    { name: 'Mocha', level: 0 },
                    { name: 'vite', level: 0 },
                    { name: 'Webpack', level: 0 },
                    { name: 'Rollup', level: 0 },
                    { name: 'ESLint', level: 0 },
                    { name: 'Prettier', level: 0 },
                    { name: 'JQuery', level: 0 },
                    { name: 'D3.js', level: 0 },
                    { name: 'Chart.js', level: 0 },
                    { name: 'Three.js', level: 0 },
                    { name: 'Redux', level: 0 },
                ],
            },
            {
                name: 'Python',
                level: 0,
                subSkills: [
                    { name: 'Django', level: 0 },
                    { name: 'FastAPI', level: 0 },
                    { name: 'Pandas', level: 0 },
                    { name: 'NumPy', level: 0 },
                    { name: 'TensorFlow', level: 0 },
                    { name: 'Matplotlib', level: 0 },
                    { name: 'PyTest', level: 0 },
                    { name: 'Jupyter', level: 0 },
                ],
            },
            {
                name: 'Java',
                level: 0,
                subSkills: [
                    { name: 'Spring', level: 0 },
                    { name: 'Maven', level: 0 },
                    { name: 'Gradle', level: 0 },
                    { name: 'JUnit', level: 0 },
                ],
            },
            { name: 'Kotlin', level: 0 },
            { name: 'C#', level: 0, subSkills: [{ name: '.NET', level: 0 }] },
            {
                name: 'C/C++',
                level: 0,
                subSkills: [
                    { name: 'Qt', level: 0 },
                    { name: 'Boost', level: 0 },
                    { name: 'OpenCV', level: 0 },
                    { name: 'STL', level: 0 },
                    { name: 'CMake', level: 0 },
                    { name: 'Make', level: 0 },
                    { name: 'Conan', level: 0 },
                    { name: 'gcc/g++', level: 0 },
                    { name: 'clang', level: 0 },
                    { name: 'gdb', level: 0 },
                    { name: 'Valgrind', level: 0 },
                ],
            },
            { name: 'Go', level: 0 },
            { name: 'Rust', level: 0 },
        ],
        additionalTools: [
            { name: 'Git', level: 0 },
            {
                name: 'Docker',
                level: 0,
                subSkills: [
                    { name: 'Docker Compose', level: 0 },
                    { name: 'Docker Swarm', level: 0 },
                    { name: 'Docker Desktop', level: 0 },
                ],
            },
            {
                name: 'Linux',
                level: 0,
                subSkills: [
                    { name: 'Bash/Shell Scripting', level: 0 },
                    { name: 'Awk', level: 0 },
                    { name: 'Sed', level: 0 },
                    { name: 'Cron', level: 0 },
                ],
            },
            { name: 'PostgreSQL', level: 0 },
            { name: 'MongoDB', level: 0 },
            { name: 'MySQL', level: 0 },
            { name: 'SQLite', level: 0 },
            { name: 'Kafka', level: 0 },
            { name: 'Elasticsearch', level: 0 },
            { name: 'OpenGL', level: 0 },
            { name: 'Antlr', level: 0 },
        ],
        webTools: [
            { name: 'Kubernetes', level: 0 },
            { name: 'Helm', level: 0 },
            { name: 'AWS', level: 0 },
            { name: 'Azure', level: 0 },
            { name: 'Redis', level: 0 },
            { name: 'Prometheus', level: 0 },
            { name: 'Grafana', level: 0 },
            { name: 'Datadog', level: 0 },
            { name: 'Keycloak', level: 0 },
            { name: 'Authelia', level: 0 },
            { name: 'Postman', level: 0 },
            { name: 'Traefik', level: 0 },
            { name: 'Caddy', level: 0 },
            { name: 'Vercel', level: 0 },
            { name: 'Netlify', level: 0 },
            { name: 'Cloudflare', level: 0 },
            { name: 'Vault', level: 0 },
        ],
        productivityTools: [
            { name: 'Jira', level: 0 },
            { name: 'Confluence', level: 0 },
            { name: 'Figma', level: 0 },
            { name: 'Miro', level: 0 },
            { name: 'Jenkins', level: 0 },
            {
                name: 'GitHub',
                level: 0,
                subSkills: [
                    { name: 'GitHub Actions', level: 0 },
                    { name: 'Dependabot', level: 0 },
                ],
            },
            {
                name: 'GitLab',
                level: 0,
                subSkills: [
                    { name: 'GitLab CI/CD', level: 0 },
                    { name: 'GitLab Runner', level: 0 },
                    { name: 'GitLab Pages', level: 0 },
                ],
            },
            { name: 'Bitbucket', level: 0 },
            { name: 'GnuPlot', level: 0 },
            { name: 'Terraform', level: 0 },
            { name: 'Nginx', level: 0 },
            { name: 'Ansible', level: 0 },
        ],
        methodologies: [
            { name: 'Xtreme Programming', level: 0 },
            { name: 'Scrum', level: 0 },
            { name: 'Kanban', level: 0 },
            { name: 'TDD', level: 0 },
            { name: 'CI/CD', level: 0 },
            { name: 'Pair Programming', level: 0 },
            {
                name: 'AI Tools',
                level: 0,
                subSkills: [
                    { name: 'ChatGPT', level: 0 },
                    { name: 'Model Context Protocol', level: 0 },
                    { name: 'Prompt Engineering', level: 0 },
                    { name: 'Codex', level: 0 },
                    { name: 'GitHub Copilot', level: 0 },
                    { name: 'Cursor', level: 0 },
                ],
            },
        ],
        ides: [
            { name: 'VS Code', level: 0 },
            { name: 'IntelliJ IDEA', level: 0 },
            { name: 'PyCharm', level: 0 },
            { name: 'WebStorm', level: 0 },
            { name: 'Eclipse', level: 0 },
            { name: 'NetBeans', level: 0 },
            { name: 'CLion', level: 0 },
            { name: 'Rider', level: 0 },
            { name: 'Visual Studio', level: 0 },
            { name: 'Xcode', level: 0 },
        ],
    };
};
